### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [Shane-Games/Cubley#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by samtaber** [comment]
Not too sure. @Shane-Games do you know what to do about this?

**Comment by Shane-Games** [comment]
Hey, that would be awesome @geopic 👍

**Comment by geopic** [comment]
Awesome, I'll start on it now.
